name: PHPUnit Tests

on:
  push:
    branches:
      - main
      - improve_ci
  pull_request:
    paths:
    - '.forgejo/workflows/phpunit-tests.yml'
    - 'includes/**'
    - 'test/unit/php**'
    - '*.php'
    - 'phpunit.xml.dist'
    - 'composer.*'

jobs:
  phpunit:
    name: PHPUnit – PHP ${{ matrix.php-version }}
    runs-on: codeberg-medium
    services:
      mariadb:
        image: mariadb
        env:
          MARIADB_DATABASE: wordpress
          MARIADB_USER: wordpress_user
          MARIADB_PASSWORD: password
          MARIADB_ROOT_PASSWORD: password
    strategy:
      matrix:
        php-version: ['8.4']
        wordpress-version: ['6.9']
    env:
      extensions: mysql, dom, iconv, json, libxml, zip
      wordpress-plugins: activitypub, gatherpress
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v6

      - name: Cache Composer
        id: cache-composer
        uses: https://code.forgejo.org/actions/cache@v4
        with:
          path: ./vendor/
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}

      - name: Setup cache environment for PHP Extensions
        id: php-extensions-cache
        uses: https://github.com/shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.extensions }}
          key: php-extensions-cache-1

      - name: Cache PHP extensions
        uses: https://code.forgejo.org/actions/cache@v4
        with:
          path: ${{ steps.php-extensions-cache.outputs.dir }}
          key: ${{ steps.php-extensions-cache.outputs.key }}
          restore-keys: ${{ steps.php-extensions-cache.outputs.key }}

      - name: Setup PHP
        uses: https://github.com/shivammathur/setup-php@2.35.5
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.extensions }}
          coverage: none
          tools: composer, cs2pr
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_FOR_GITHUB }}

      - name: Install Composer dependencies for PHP
        if: steps.cache-composer.outputs.cache-hit != 'true'
        uses: https://github.com/ramsey/composer-install@v3
        with:
          composer_options: --optimize-autoloader --prefer-dist
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.ACCESS_TOKEN_FOR_GITHUB }}"}}'
          GITHUB_TOKEN: ${{ env.ACCESS_TOKEN_FOR_GITHUB }}

      - name: Get cache key for WordPress
        uses: https://code.forgejo.org/linos/setup-wordpress@v1.2.2
        id: wordpress-info
        with:
          wordpress-plugins: ${{ env.wordpress-plugins }}
          only-output-cache-key: true

      - name: Cache WordPress setup including PHPUNit and plugins
        id: cache-wordpress
        uses: https://code.forgejo.org/actions/cache@v4
        with:
          path: ${{ steps.wordpress-info.outputs.wordpress-dir }}
          key: ${{ steps.wordpress-info.outputs.cache-key }}

      - name: Setup WordPress
        if: steps.cache-wordpress.outputs.cache-hit != 'true'
        uses: https://code.forgejo.org/linos/setup-wordpress@v1.2.2
        with:
          wordpress-plugins: ${{ env.wordpress-plugins }}
          db-name: wordpress
          db-user: wordpress_user
          db-pass: password
          db-host: mariadb
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.ACCESS_TOKEN_FOR_GITHUB }}"}}'
          GITHUB_TOKEN: ${{ env.ACCESS_TOKEN_FOR_GITHUB }}

      - name: PHPUnit
        run: ./vendor/bin/phpunit
        env:
          PHP_VERSION: ${{ matrix.php-versions }}
          WP_ENVIRONMENT_TYPE: production
          WP_TESTS_DIR: ${{ steps.wordpress-setup.outputs.wordpress-phpunit-dir }}
